version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: momentum-scanner-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: momentum_scanner
      MYSQL_USER: momentum_user
      MYSQL_PASSWORD: momentum_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init:/docker-entrypoint-initdb.d
    networks:
      - momentum-network
    command: --default-authentication-plugin=mysql_native_password

  # Backend API (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: momentum-scanner-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://momentum_user:momentum_password@mysql:3306/momentum_scanner
      - PYTHONPATH=/app
    depends_on:
      - mysql
    networks:
      - momentum-network
    volumes:
      - ./backend:/app

  # Frontend (React/Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: momentum-scanner-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - momentum-network

volumes:
  mysql_data:
    driver: local

networks:
  momentum-network:
    driver: bridge
