import type { Ticker } from "../components/TickerTable";

export const generateDummyTickers = (): Ticker[] => [
  {
    medal: "🥇",
    ticker: "BTC",
    market: "Binance",
    price: (1000000 + Math.random() * 1000000).toFixed(2),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥈",
    ticker: "ETH",
    market: "Bybit",
    price: (2000 + Math.random() * 100).toFixed(2),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "BNB",
    market: "OKX",
    price: (300 + Math.random() * 20).toFixed(2),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "TOKAMAK",
    market: "Upbit",
    price: (100 + Math.random() * 10).toFixed(2),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "XRP",
    market: "Binance",
    price: (0.5 + Math.random() * 0.2).toFixed(4),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "ADA",
    market: "Bybit",
    price: (0.3 + Math.random() * 0.1).toFixed(4),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "DOGE",
    market: "OKX",
    price: (0.08 + Math.random() * 0.02).toFixed(4),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "MAGIC",
    market: "Binance",
    price: (1 + Math.random() * 0.2).toFixed(4),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "DOT",
    market: "Binance",
    price: (5 + Math.random() * 1).toFixed(2),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "LTC",
    market: "Bybit",
    price: (80 + Math.random() * 10).toFixed(2),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "TRX",
    market: "OKX",
    price: (0.07 + Math.random() * 0.01).toFixed(4),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "AVAX",
    market: "Bybit",
    price: (15 + Math.random() * 2).toFixed(2),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "SHIB",
    market: "Binance",
    price: (0.00001 + Math.random() * 0.000001).toFixed(8),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "UNI",
    market: "Bybit",
    price: (6 + Math.random() * 1).toFixed(2),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "LINK",
    market: "OKX",
    price: (7 + Math.random() * 1).toFixed(2),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
  {
    medal: "🥉",
    ticker: "ATOM",
    market: "Bybit",
    price: (10 + Math.random() * 2).toFixed(2),
    pctChange: (Math.random() * 10 - 5).toFixed(2),
    volPctChange: (Math.random() * 20 - 10).toFixed(2),
    float: (Math.random() * 100000).toFixed(0),
  },
];
